### PR TITLE
[WIP] Fix incorrect pattern when given full NEVRA

### PR DESCRIPTION
**Pull request by jturel**
https://projects.theforeman.org/issues/24523

### CODE REVIEW

**Comment by jturel** [comment]
@jortel 

The test code added reproduces the issue (when using the dockerized tests here) =>

```
======================================================================
ERROR: test_install_nevra_name (test_katello.test_agent.test_pulp.test_libyum.TestPackage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/test/test_katello/test_agent/test_pulp/test_libyum.py", line 30, in test_install_nevra_name
    assert self.package.install([pattern])   
  File "/usr/lib/python2.7/site-packages/katello_agent-3.3.4-py2.7.egg/katello/agent/pulp/libyum.py", line 266, in install
    raise caught                              
yum.Errors.InstallError: *:walrus-0.71-1.noarch-*-*.*: No package(s) available to install
 ```

It seems like gofer is getting a unit which only has the `name` key and it actually contains the full nevra string.

Can you tell me if gofer should be getting a unit with a full dict representing the nevra from pulp, or should we be parsing out the Pattern given some string?

**Comment by jortel** [comment]
By gofer, I assume you mean the rpm handler code.  The content unit often only contains partial pattern (like just name) and the handler adds the wildcard syntax for yum.

**Comment by jturel** [comment]
User is trying to install a package from the katello ui using the agent and they're giving a NVRA - ie walrus-0.71-1.noarch and based on the end result (and the tests presented here) I think the unit dict looks like:

```
dict(name="walrus-0.71-1.noarch", epoch="*", version="*", release="*", arch="*")
```

rather than (which I think it's supposed to be):

```
dict(name="walrus", epoch="*", version="0.71", release="1", arch="noarch")
```

**Comment by jturel** [comment]
Indeed the dispatcher is getting a unit that looks like:

```
[INFO][worker-0] katello.agent.pulp.dispatcher:77 - [{u'name': u'walrus-0.71-1.noarch'}]
```

**Pull request closed without merging**
