### PR TITLE
Rename dnf_plugins to the correct dnf-plugins

### PR DESCRIPTION
**Pull request by ianballou**
This is the full future fix for the band-aid fix here: https://github.com/theforeman/foreman-packaging/pull/9304

`dnf_plugins` was named incorrectly. I'm not sure why this was suddenly an issue since the folder was always named that way, perhaps there was a packaging change that broke it.

We should do another release of k-h-t after this PR is merged.

To test, first try installing katello-host-tools with version 4.3.2. Traces will not be uploaded. To verify the fix, simply do the following:

```
mv /usr/lib/python3.6/site-packages/dnf_plugins/tracer_upload.py /usr/lib/python3.6/site-packages/dnf-plugins/tracer_upload.py
```

### CODE REVIEW

**Comment by evgeni** [comment]
This PR *adds* files, not *moves* them ;-)

**Comment by lfu** [comment]
Why do we keep `dnf_plugins` directory?

**Comment by ianballou** [comment]
Now it moves them!

**Review by evgeni — APPROVED** [review]

**Review by lfu — APPROVED** [review]
LGTM 👍🏻

**Comment by evgeni** [comment]
> Looks like the tests are going to need an update.

https://github.com/Katello/katello-host-tools/blob/eab28c632e014bd3624a74a3b685ce1f1fc911cc/test/dnf_plugins/test_tracer_upload.py#L7

**Review by chris1984 — APPROVED** [review]

**Comment by chris1984** [comment]
Once green, will merge

**Comment by chris1984** [comment]
Opensuse test failure is unrelated. Thanks all

**Pull request merged**
