### PR TITLE
3.3.5 Release

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by sjha4** [comment]
jturel: Are we planning to go with this for 3.8 GA?

**Comment by jturel** [comment]
@sjha4 yes! let me open a packaging PR

**Comment by achevalet** [comment]
Hey,
`Package katello-host-tools-3.3.5-3.el7.noarch.rpm is not signed`
normal?

**Comment by jturel** [comment]
Hi @achevalet - can you confirm where you've acquired the package from?

Perhaps https://fedorapeople.org/groups/katello/releases/yum/3.8/client/f27/x86_64/ ?

**Comment by achevalet** [comment]
From the 3.7 release: https://fedorapeople.org/groups/katello/releases/yum/3.7/client/el7/x86_64
I didn't try from 3.8.

**Comment by jturel** [comment]
Should be fixed - check it out!

**Comment by achevalet** [comment]
All green, thank you @jturel !

**Comment by jturel** [comment]
Hey @achevalet sorry for the delay on this. This should be corrected now for both 3.7 and 3.8. I really appreciate the report.

In the future you are likely to get a faster response by letting folks over in our support area[1] know the issues you encounter as this project is part of the Foreman ecosystem. Just letting you know in case you'd never come across our Discourse!

[1] https://community.theforeman.org/c/support

**Comment by achevalet** [comment]
Thank you @jturel! Next time I will come in the support area.

**Pull request merged**
