### PR TITLE
Fixes #27650 - Handles combined profile uploads

### PR DESCRIPTION
**Pull request by parthaa**
Subscription Manager 1.23-2 and above have the ability to generate a
profile.json that combines package profile, enabled repositories profile
and modulemd profiles. Katello Host tools at present is unable to take
advantage of this facility. So 2 sets of reports related to enabled
repositories are sent to the server.
This commit does the following
1) Removes the package_profile_on_trans check and instead always defers
to subscription manager to handle it
2) Checks if combined profiles feature is enabled by checking if
rhsm.profile.EnabledRepos is available.
3) If Combined profiles are available then defers the enabled repos
upload to subscription manager as well
4) Makes the remove_cache rm the profile.json instead of whereever the
cache was before. This remove_cache is used in the "force" calls.
katello-package-upload -f and katello-enabled-repos-upload -f
operations.

Subscription manager sends information to the server only if the cache
changes and hence unnecessary calls to the server are avoided.

### CODE REVIEW

**Comment by jturel** [comment]
@parthaa at a glance it looks good - testing now. can you fix up the tests?

**Comment by parthaa** [comment]
Closing this since subman handles this situation

**Comment by parthaa** [comment]
Steps to reproduce:
On a RHEL 7.7 system with katello-host-tools installed and registered to satellite:
1) katello-package-upload -f # This succeeds in uploading a profile the first time (creating a "Combined Profile Update *" task in Monitor > Tasks)
2) katello-package-upload -f # This (and subsequent calls with no package installations or removals) fails to create another "Combined Profile Update *" task in Monitor > Tasks

Expected Results:
On step 2 there should be another "Combined Profile Update *" task created in Monitor > Tasks

**Comment by jturel** [comment]
Works well. Looks like there are some lints to address in the files you altered:

```
[jturel@strangeways katello-host-tools]$ flake8 src/katello/packages.py src/katello/constants.py src/katello/repos.py src/katello/utils.py --ignore=E501
src/katello/packages.py:5:1: I101 Imported names are in the wrong order. Should be DISABLE_PACKAGE_PROFILE_VAR, PACKAGE_CACHE_FILE, PACKAGE_PROFILE_PLUGIN_CONF, PROFILE_CACHE_FILE
src/katello/packages.py:7:1: I101 Imported names are in the wrong order. Should be combined_profiles_enabled, plugin_enabled
src/katello/packages.py:9:1: E302 expected 2 blank lines, found 1
src/katello/packages.py:11:7: E111 indentation is not a multiple of four
src/katello/packages.py:23:8: E111 indentation is not a multiple of four
src/katello/repos.py:4:1: I100 Import statements are in the wrong order. 'import os.path' should be before 'import sys'
src/katello/repos.py:6:1: I101 Imported names are in the wrong order. Should be DISABLE_ENABLE_REPOS_VAR, ENABLED_REPOS_CACHE_FILE, ENABLED_REPOS_PLUGIN_CONF, PROFILE_CACHE_FILE
src/katello/repos.py:7:1: I101 Imported names are in the wrong order. Should be get_manager, get_uep, lookup_consumer_id
src/katello/repos.py:8:1: I101 Imported names are in the wrong order. Should be combined_profiles_enabled, plugin_enabled
src/katello/repos.py:54:1: E302 expected 2 blank lines, found 1
src/katello/repos.py:63:12: E111 indentation is not a multiple of four
src/katello/utils.py:4:1: F401 'rhsm.config as rhsmConfig' imported but unused
src/katello/utils.py:9:5: F401 'ConfigParser.NoOptionError' imported but unused
src/katello/utils.py:21:5: E722 do not use bare 'except'
src/katello/utils.py:28:1: E302 expected 2 blank lines, found 1
src/katello/utils.py:30:9: F401 'rhsm.profile.EnabledRepos' imported but unused
```

**Comment by parthaa** [comment]
> Works well. Looks like there are some lints to address in the files you altered:

should be addressed

**Comment by jturel** [comment]
I still see some.

```
[jturel@strangeways katello-host-tools]$ flake8 src/katello/packages.py src/katello/constants.py src/katello/repos.py src/katello/utils.py --ignore=E501
src/katello/packages.py:4:1: I101 Imported names are in the wrong order. Should be DISABLE_PACKAGE_PROFILE_VAR, PACKAGE_CACHE_FILE, PACKAGE_PROFILE_PLUGIN_CONF, PROFILE_CACHE_FILE
src/katello/packages.py:4:1: I201 Missing newline between import groups. 'from katello.constants import PACKAGE_CACHE_FILE, PACKAGE_PROFILE_PLUGIN_CONF, DISABLE_PACKAGE_PROFILE_VAR, PROFILE_CACHE_FILE' is identified as Third Party and 'import sys' is identified as Stdlib.
src/katello/packages.py:6:1: I101 Imported names are in the wrong order. Should be combined_profiles_enabled, plugin_enabled
src/katello/repos.py:4:1: I100 Import statements are in the wrong order. 'import os.path' should be before 'import sys'
src/katello/repos.py:6:1: I101 Imported names are in the wrong order. Should be DISABLE_ENABLE_REPOS_VAR, ENABLED_REPOS_CACHE_FILE, ENABLED_REPOS_PLUGIN_CONF, PROFILE_CACHE_FILE
src/katello/repos.py:7:1: I101 Imported names are in the wrong order. Should be get_manager, get_uep, lookup_consumer_id
src/katello/repos.py:8:1: I101 Imported names are in the wrong order. Should be combined_profiles_enabled, plugin_enabled
```

You can see the command I used to generate the output. In the future I'll make travis fail on this

**Pull request merged**
